### ISSUE TITLE
Logo adjustments

### ISSUE THREAD

**Issue by KeyboardRage** [ziglang/logo#5]
Hi, I saw an opportunity for further adjustments of the logo and thought I'd give it a go.

![New logo suggestion](https://i.thevirt.us/04/zig_logo_colour_small.png)

I tried to give it a bit more consistency and have the logotype resonate with the logo symbol. I also based logo symbol on the golden ratio, as well as for the downsizing to determine some of margins. Furthermore I adjusted angles to be consistent across logo symbol and type. ([margins, sizes, etc screenshot](https://i.thevirt.us/04/zig_suggestion_showcase.png))

The font is based on the font family [Montserrat ](https://fonts.google.com/specimen/Montserrat)(with modifications), under the [SIL Open Font License, Version 1.1](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL).

Attached is a pack of PNG's of the logo symbol and full logo, as SVG and PNG, in colours/black/white—should you want to use the adjustments.
[zig_pack.zip](https://github.com/ziglang/zig/files/4536620/zig_pack.zip)

It would also be beneficial to make dedicated versions for smaller scales, like favicon. SVG code could also use some cleanup, as it is exported directly from Adobe Illustrator, and colour profile embedded into the images.

If you need some adjustments to be made, just let me know.

**Comment by andrewrk** [comment]
Wow that looks great to me! I love it!

Here's the path forward on this:

 * [ ] As a sanity check, I will ask for some sign-off from core Zig team members, make sure people are generally on board with it.
 * [ ] Figure out how it will work on dark backgrounds. (picture attached of what it currently looks like)
![Screenshot_2020-04-26_19-13-18](https://user-images.githubusercontent.com/106511/80322263-ff668b80-87f1-11ea-9934-942608b6f5a9.png)
do we need an alternate version for dark backgrounds?
 * [ ] Agree to release the assets under the license listed in this repo (I'm happy to take counter proposals for what license to use)
 * [ ] Turn this issue into a pull request, updating the canonical assets, so that I can simply click "merge".

**Comment by KeyboardRage** [comment]
Great! Yes, generally you have different versions for dark/light backgrounds, combined with various sizes of those.

I'm fine with whatever license you see fit for this.

I can optimize the SVG sizes, have done it a few times myself in combination with [SVGOMG](https://jakearchibald.github.io/svgomg/) and further minor edits to the SVG—as well as do the edits to assets.

Will see if I can't get started on these things starting tomorrow, hopefully be done come weekend.

**Comment by yewpad** [comment]
![image](https://user-images.githubusercontent.com/54741912/80427128-61ed8380-88e7-11ea-96f1-09d79c709fcf.png)

Took an attempt to copy/paste the logo into Zig's current website. Adjusted the height a bit and added a `10px` padding. Looks fantastic!

**Comment by lukeholder** [comment]
Love the end result @KeyboardRage - great work!
